// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NetParentOld.proto

package com.module.net;

public final class NetParentOld {
  private NetParentOld() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NetCommondOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string sn = 1;
    /**
     * <code>optional string sn = 1;</code>
     */
    boolean hasSn();
    /**
     * <code>optional string sn = 1;</code>
     */
    String getSn();
    /**
     * <code>optional string sn = 1;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    // optional int32 cmd = 2;
    /**
     * <code>optional int32 cmd = 2;</code>
     */
    boolean hasCmd();
    /**
     * <code>optional int32 cmd = 2;</code>
     */
    int getCmd();

    // optional int32 status = 3;
    /**
     * <code>optional int32 status = 3;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3;</code>
     */
    int getStatus();

    // optional int32 time = 4;
    /**
     * <code>optional int32 time = 4;</code>
     */
    boolean hasTime();
    /**
     * <code>optional int32 time = 4;</code>
     */
    int getTime();

    // optional bytes obj = 5;
    /**
     * <code>optional bytes obj = 5;</code>
     */
    boolean hasObj();
    /**
     * <code>optional bytes obj = 5;</code>
     */
    com.google.protobuf.ByteString getObj();

    // optional int32 uid = 6;
    /**
     * <code>optional int32 uid = 6;</code>
     */
    boolean hasUid();
    /**
     * <code>optional int32 uid = 6;</code>
     */
    int getUid();

    // optional int32 seq = 7;
    /**
     * <code>optional int32 seq = 7;</code>
     */
    boolean hasSeq();
    /**
     * <code>optional int32 seq = 7;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code NetCommond}
   */
  public static final class NetCommond extends
      com.google.protobuf.GeneratedMessage
      implements NetCommondOrBuilder {
    // Use NetCommond.newBuilder() to construct.
    private NetCommond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetCommond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetCommond defaultInstance;
    public static NetCommond getDefaultInstance() {
      return defaultInstance;
    }

    public NetCommond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetCommond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sn_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              status_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              time_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              obj_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              uid_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              seq_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetParentOld.internal_static_NetCommond_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetParentOld.internal_static_NetCommond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetCommond.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NetCommond> PARSER =
        new com.google.protobuf.AbstractParser<NetCommond>() {
      public NetCommond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetCommond(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NetCommond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string sn = 1;
    public static final int SN_FIELD_NUMBER = 1;
    private Object sn_;
    /**
     * <code>optional string sn = 1;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    public String getSn() {
      Object ref = sn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      Object ref = sn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 cmd = 2;
    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 2;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cmd = 2;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional int32 status = 3;
    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>optional int32 status = 3;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 status = 3;</code>
     */
    public int getStatus() {
      return status_;
    }

    // optional int32 time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private int time_;
    /**
     * <code>optional int32 time = 4;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 time = 4;</code>
     */
    public int getTime() {
      return time_;
    }

    // optional bytes obj = 5;
    public static final int OBJ_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString obj_;
    /**
     * <code>optional bytes obj = 5;</code>
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes obj = 5;</code>
     */
    public com.google.protobuf.ByteString getObj() {
      return obj_;
    }

    // optional int32 uid = 6;
    public static final int UID_FIELD_NUMBER = 6;
    private int uid_;
    /**
     * <code>optional int32 uid = 6;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 uid = 6;</code>
     */
    public int getUid() {
      return uid_;
    }

    // optional int32 seq = 7;
    public static final int SEQ_FIELD_NUMBER = 7;
    private int seq_;
    /**
     * <code>optional int32 seq = 7;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 seq = 7;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private void initFields() {
      sn_ = "";
      cmd_ = 0;
      status_ = 0;
      time_ = 0;
      obj_ = com.google.protobuf.ByteString.EMPTY;
      uid_ = 0;
      seq_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, obj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, uid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, seq_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, time_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, obj_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, uid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, seq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NetCommond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetCommond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetCommond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetCommond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetCommond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetCommond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetCommond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetCommond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetCommond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetCommondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetParentOld.internal_static_NetCommond_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetParentOld.internal_static_NetCommond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetCommond.class, Builder.class);
      }

      // Construct using com.module.net.NetParentOld.NetCommond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        obj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetParentOld.internal_static_NetCommond_descriptor;
      }

      public NetCommond getDefaultInstanceForType() {
        return NetCommond.getDefaultInstance();
      }

      public NetCommond build() {
        NetCommond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetCommond buildPartial() {
        NetCommond result = new NetCommond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.obj_ = obj_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetCommond) {
          return mergeFrom((NetCommond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetCommond other) {
        if (other == NetCommond.getDefaultInstance()) return this;
        if (other.hasSn()) {
          bitField0_ |= 0x00000001;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasObj()) {
          setObj(other.getObj());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetCommond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetCommond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string sn = 1;
      private Object sn_ = "";
      /**
       * <code>optional string sn = 1;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public String getSn() {
        Object ref = sn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder setSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 1;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }

      // optional int32 cmd = 2;
      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 2;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 2;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional int32 status = 3;
      private int status_ ;
      /**
       * <code>optional int32 status = 3;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000004;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 3;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional int32 time = 4;
      private int time_ ;
      /**
       * <code>optional int32 time = 4;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000008;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time = 4;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        time_ = 0;
        onChanged();
        return this;
      }

      // optional bytes obj = 5;
      private com.google.protobuf.ByteString obj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes obj = 5;</code>
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes obj = 5;</code>
       */
      public com.google.protobuf.ByteString getObj() {
        return obj_;
      }
      /**
       * <code>optional bytes obj = 5;</code>
       */
      public Builder setObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes obj = 5;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000010);
        obj_ = getDefaultInstance().getObj();
        onChanged();
        return this;
      }

      // optional int32 uid = 6;
      private int uid_ ;
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000020;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 6;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000020);
        uid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 seq = 7;
      private int seq_ ;
      /**
       * <code>optional int32 seq = 7;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 seq = 7;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>optional int32 seq = 7;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000040;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 seq = 7;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000040);
        seq_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetCommond)
    }

    static {
      defaultInstance = new NetCommond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetCommond)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetCommond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetCommond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030proto/NetParentOld.proto\"j\n\nNetCommond" +
      "\022\n\n\002sn\030\001 \001(\t\022\013\n\003cmd\030\002 \001(\005\022\016\n\006status\030\003 \001(" +
      "\005\022\014\n\004time\030\004 \001(\005\022\013\n\003obj\030\005 \001(\014\022\013\n\003uid\030\006 \001(" +
      "\005\022\013\n\003seq\030\007 \001(\005B\036\n\016com.module.netB\014NetPar" +
      "entOld"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetCommond_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetCommond_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetCommond_descriptor,
              new String[] { "Sn", "Cmd", "Status", "Time", "Obj", "Uid", "Seq", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
