// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NetResult.proto

package com.module.net;

public final class NetResult {
  private NetResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RQMjREsultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 flag = 1;
    /**
     * <code>optional int32 flag = 1;</code>
     */
    boolean hasFlag();
    /**
     * <code>optional int32 flag = 1;</code>
     */
    int getFlag();

    // repeated .NetMjUserResult results = 2;
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    java.util.List<NetMjUserResult>
        getResultsList();
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    NetMjUserResult getResults(int index);
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    int getResultsCount();
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    java.util.List<? extends NetMjUserResultOrBuilder>
        getResultsOrBuilderList();
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    NetMjUserResultOrBuilder getResultsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code RQMjREsult}
   */
  public static final class RQMjREsult extends
      com.google.protobuf.GeneratedMessage
      implements RQMjREsultOrBuilder {
    // Use RQMjREsult.newBuilder() to construct.
    private RQMjREsult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RQMjREsult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RQMjREsult defaultInstance;
    public static RQMjREsult getDefaultInstance() {
      return defaultInstance;
    }

    public RQMjREsult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RQMjREsult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              flag_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                results_ = new java.util.ArrayList<NetMjUserResult>();
                mutable_bitField0_ |= 0x00000002;
              }
              results_.add(input.readMessage(NetMjUserResult.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetResult.internal_static_RQMjREsult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetResult.internal_static_RQMjREsult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RQMjREsult.class, Builder.class);
    }

    public static com.google.protobuf.Parser<RQMjREsult> PARSER =
        new com.google.protobuf.AbstractParser<RQMjREsult>() {
      public RQMjREsult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RQMjREsult(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<RQMjREsult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 flag = 1;
    public static final int FLAG_FIELD_NUMBER = 1;
    private int flag_;
    /**
     * <code>optional int32 flag = 1;</code>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 flag = 1;</code>
     */
    public int getFlag() {
      return flag_;
    }

    // repeated .NetMjUserResult results = 2;
    public static final int RESULTS_FIELD_NUMBER = 2;
    private java.util.List<NetMjUserResult> results_;
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    public java.util.List<NetMjUserResult> getResultsList() {
      return results_;
    }
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    public java.util.List<? extends NetMjUserResultOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    public NetMjUserResult getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated .NetMjUserResult results = 2;</code>
     */
    public NetMjUserResultOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private void initFields() {
      flag_ = 0;
      results_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, flag_);
      }
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(2, results_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, flag_);
      }
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, results_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static RQMjREsult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RQMjREsult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RQMjREsult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RQMjREsult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RQMjREsult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RQMjREsult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static RQMjREsult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static RQMjREsult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static RQMjREsult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static RQMjREsult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(RQMjREsult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RQMjREsult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements RQMjREsultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetResult.internal_static_RQMjREsult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetResult.internal_static_RQMjREsult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RQMjREsult.class, Builder.class);
      }

      // Construct using com.module.net.NetResult.RQMjREsult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetResult.internal_static_RQMjREsult_descriptor;
      }

      public RQMjREsult getDefaultInstanceForType() {
        return RQMjREsult.getDefaultInstance();
      }

      public RQMjREsult build() {
        RQMjREsult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public RQMjREsult buildPartial() {
        RQMjREsult result = new RQMjREsult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.flag_ = flag_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RQMjREsult) {
          return mergeFrom((RQMjREsult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RQMjREsult other) {
        if (other == RQMjREsult.getDefaultInstance()) return this;
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000002);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RQMjREsult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RQMjREsult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 flag = 1;
      private int flag_ ;
      /**
       * <code>optional int32 flag = 1;</code>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 flag = 1;</code>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>optional int32 flag = 1;</code>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000001;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flag = 1;</code>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        onChanged();
        return this;
      }

      // repeated .NetMjUserResult results = 2;
      private java.util.List<NetMjUserResult> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          results_ = new java.util.ArrayList<NetMjUserResult>(results_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          NetMjUserResult, NetMjUserResult.Builder, NetMjUserResultOrBuilder> resultsBuilder_;

      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public java.util.List<NetMjUserResult> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public NetMjUserResult getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder setResults(
          int index, NetMjUserResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder setResults(
          int index, NetMjUserResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder addResults(NetMjUserResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder addResults(
          int index, NetMjUserResult value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder addResults(
          NetMjUserResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder addResults(
          int index, NetMjUserResult.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder addAllResults(
          Iterable<? extends NetMjUserResult> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          super.addAll(values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public NetMjUserResult.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public NetMjUserResultOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public java.util.List<? extends NetMjUserResultOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public NetMjUserResult.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            NetMjUserResult.getDefaultInstance());
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public NetMjUserResult.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, NetMjUserResult.getDefaultInstance());
      }
      /**
       * <code>repeated .NetMjUserResult results = 2;</code>
       */
      public java.util.List<NetMjUserResult.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          NetMjUserResult, NetMjUserResult.Builder, NetMjUserResultOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              NetMjUserResult, NetMjUserResult.Builder, NetMjUserResultOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:RQMjREsult)
    }

    static {
      defaultInstance = new RQMjREsult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:RQMjREsult)
  }

  public interface NetMjUserResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .NetKvData scores = 1;
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    java.util.List<NetGame.NetKvData>
        getScoresList();
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    NetGame.NetKvData getScores(int index);
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    int getScoresCount();
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getScoresOrBuilderList();
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    NetGame.NetKvDataOrBuilder getScoresOrBuilder(
            int index);

    // repeated .NetKvData records = 2;
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    java.util.List<NetGame.NetKvData>
        getRecordsList();
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    NetGame.NetKvData getRecords(int index);
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    int getRecordsCount();
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getRecordsOrBuilderList();
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    NetGame.NetKvDataOrBuilder getRecordsOrBuilder(
            int index);

    // repeated int32 data = 3;
    /**
     * <code>repeated int32 data = 3;</code>
     */
    java.util.List<Integer> getDataList();
    /**
     * <code>repeated int32 data = 3;</code>
     */
    int getDataCount();
    /**
     * <code>repeated int32 data = 3;</code>
     */
    int getData(int index);

    // optional int32 roldId = 4;
    /**
     * <code>optional int32 roldId = 4;</code>
     */
    boolean hasRoldId();
    /**
     * <code>optional int32 roldId = 4;</code>
     */
    int getRoldId();

    // repeated .NetKvData hands = 5;
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    java.util.List<NetGame.NetKvData>
        getHandsList();
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    NetGame.NetKvData getHands(int index);
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    int getHandsCount();
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getHandsOrBuilderList();
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    NetGame.NetKvDataOrBuilder getHandsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code NetMjUserResult}
   */
  public static final class NetMjUserResult extends
      com.google.protobuf.GeneratedMessage
      implements NetMjUserResultOrBuilder {
    // Use NetMjUserResult.newBuilder() to construct.
    private NetMjUserResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetMjUserResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetMjUserResult defaultInstance;
    public static NetMjUserResult getDefaultInstance() {
      return defaultInstance;
    }

    public NetMjUserResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetMjUserResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                scores_ = new java.util.ArrayList<NetGame.NetKvData>();
                mutable_bitField0_ |= 0x00000001;
              }
              scores_.add(input.readMessage(NetGame.NetKvData.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                records_ = new java.util.ArrayList<NetGame.NetKvData>();
                mutable_bitField0_ |= 0x00000002;
              }
              records_.add(input.readMessage(NetGame.NetKvData.PARSER, extensionRegistry));
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                data_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              data_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                data_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                data_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000001;
              roldId_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                hands_ = new java.util.ArrayList<NetGame.NetKvData>();
                mutable_bitField0_ |= 0x00000010;
              }
              hands_.add(input.readMessage(NetGame.NetKvData.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = java.util.Collections.unmodifiableList(scores_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          records_ = java.util.Collections.unmodifiableList(records_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          hands_ = java.util.Collections.unmodifiableList(hands_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetResult.internal_static_NetMjUserResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetResult.internal_static_NetMjUserResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetMjUserResult.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NetMjUserResult> PARSER =
        new com.google.protobuf.AbstractParser<NetMjUserResult>() {
      public NetMjUserResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetMjUserResult(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NetMjUserResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .NetKvData scores = 1;
    public static final int SCORES_FIELD_NUMBER = 1;
    private java.util.List<NetGame.NetKvData> scores_;
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    public java.util.List<NetGame.NetKvData> getScoresList() {
      return scores_;
    }
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    public java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getScoresOrBuilderList() {
      return scores_;
    }
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    public int getScoresCount() {
      return scores_.size();
    }
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    public NetGame.NetKvData getScores(int index) {
      return scores_.get(index);
    }
    /**
     * <code>repeated .NetKvData scores = 1;</code>
     */
    public NetGame.NetKvDataOrBuilder getScoresOrBuilder(
        int index) {
      return scores_.get(index);
    }

    // repeated .NetKvData records = 2;
    public static final int RECORDS_FIELD_NUMBER = 2;
    private java.util.List<NetGame.NetKvData> records_;
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    public java.util.List<NetGame.NetKvData> getRecordsList() {
      return records_;
    }
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    public java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getRecordsOrBuilderList() {
      return records_;
    }
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    public int getRecordsCount() {
      return records_.size();
    }
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    public NetGame.NetKvData getRecords(int index) {
      return records_.get(index);
    }
    /**
     * <code>repeated .NetKvData records = 2;</code>
     */
    public NetGame.NetKvDataOrBuilder getRecordsOrBuilder(
        int index) {
      return records_.get(index);
    }

    // repeated int32 data = 3;
    public static final int DATA_FIELD_NUMBER = 3;
    private java.util.List<Integer> data_;
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public java.util.List<Integer>
        getDataList() {
      return data_;
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated int32 data = 3;</code>
     */
    public int getData(int index) {
      return data_.get(index);
    }

    // optional int32 roldId = 4;
    public static final int ROLDID_FIELD_NUMBER = 4;
    private int roldId_;
    /**
     * <code>optional int32 roldId = 4;</code>
     */
    public boolean hasRoldId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 roldId = 4;</code>
     */
    public int getRoldId() {
      return roldId_;
    }

    // repeated .NetKvData hands = 5;
    public static final int HANDS_FIELD_NUMBER = 5;
    private java.util.List<NetGame.NetKvData> hands_;
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    public java.util.List<NetGame.NetKvData> getHandsList() {
      return hands_;
    }
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    public java.util.List<? extends NetGame.NetKvDataOrBuilder>
        getHandsOrBuilderList() {
      return hands_;
    }
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    public int getHandsCount() {
      return hands_.size();
    }
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    public NetGame.NetKvData getHands(int index) {
      return hands_.get(index);
    }
    /**
     * <code>repeated .NetKvData hands = 5;</code>
     */
    public NetGame.NetKvDataOrBuilder getHandsOrBuilder(
        int index) {
      return hands_.get(index);
    }

    private void initFields() {
      scores_ = java.util.Collections.emptyList();
      records_ = java.util.Collections.emptyList();
      data_ = java.util.Collections.emptyList();
      roldId_ = 0;
      hands_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < scores_.size(); i++) {
        output.writeMessage(1, scores_.get(i));
      }
      for (int i = 0; i < records_.size(); i++) {
        output.writeMessage(2, records_.get(i));
      }
      for (int i = 0; i < data_.size(); i++) {
        output.writeInt32(3, data_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(4, roldId_);
      }
      for (int i = 0; i < hands_.size(); i++) {
        output.writeMessage(5, hands_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < scores_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, scores_.get(i));
      }
      for (int i = 0; i < records_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, records_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < data_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(data_.get(i));
        }
        size += dataSize;
        size += 1 * getDataList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, roldId_);
      }
      for (int i = 0; i < hands_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, hands_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NetMjUserResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMjUserResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMjUserResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetMjUserResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetMjUserResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetMjUserResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetMjUserResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetMjUserResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetMjUserResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetMjUserResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetMjUserResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetMjUserResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetMjUserResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetResult.internal_static_NetMjUserResult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetResult.internal_static_NetMjUserResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetMjUserResult.class, Builder.class);
      }

      // Construct using com.module.net.NetResult.NetMjUserResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getScoresFieldBuilder();
          getRecordsFieldBuilder();
          getHandsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          scoresBuilder_.clear();
        }
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          recordsBuilder_.clear();
        }
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        roldId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (handsBuilder_ == null) {
          hands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          handsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetResult.internal_static_NetMjUserResult_descriptor;
      }

      public NetMjUserResult getDefaultInstanceForType() {
        return NetMjUserResult.getDefaultInstance();
      }

      public NetMjUserResult build() {
        NetMjUserResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetMjUserResult buildPartial() {
        NetMjUserResult result = new NetMjUserResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (scoresBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            scores_ = java.util.Collections.unmodifiableList(scores_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.scores_ = scores_;
        } else {
          result.scores_ = scoresBuilder_.build();
        }
        if (recordsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            records_ = java.util.Collections.unmodifiableList(records_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.records_ = records_;
        } else {
          result.records_ = recordsBuilder_.build();
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = java.util.Collections.unmodifiableList(data_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roldId_ = roldId_;
        if (handsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            hands_ = java.util.Collections.unmodifiableList(hands_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.hands_ = hands_;
        } else {
          result.hands_ = handsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetMjUserResult) {
          return mergeFrom((NetMjUserResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetMjUserResult other) {
        if (other == NetMjUserResult.getDefaultInstance()) return this;
        if (scoresBuilder_ == null) {
          if (!other.scores_.isEmpty()) {
            if (scores_.isEmpty()) {
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureScoresIsMutable();
              scores_.addAll(other.scores_);
            }
            onChanged();
          }
        } else {
          if (!other.scores_.isEmpty()) {
            if (scoresBuilder_.isEmpty()) {
              scoresBuilder_.dispose();
              scoresBuilder_ = null;
              scores_ = other.scores_;
              bitField0_ = (bitField0_ & ~0x00000001);
              scoresBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getScoresFieldBuilder() : null;
            } else {
              scoresBuilder_.addAllMessages(other.scores_);
            }
          }
        }
        if (recordsBuilder_ == null) {
          if (!other.records_.isEmpty()) {
            if (records_.isEmpty()) {
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRecordsIsMutable();
              records_.addAll(other.records_);
            }
            onChanged();
          }
        } else {
          if (!other.records_.isEmpty()) {
            if (recordsBuilder_.isEmpty()) {
              recordsBuilder_.dispose();
              recordsBuilder_ = null;
              records_ = other.records_;
              bitField0_ = (bitField0_ & ~0x00000002);
              recordsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRecordsFieldBuilder() : null;
            } else {
              recordsBuilder_.addAllMessages(other.records_);
            }
          }
        }
        if (!other.data_.isEmpty()) {
          if (data_.isEmpty()) {
            data_ = other.data_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureDataIsMutable();
            data_.addAll(other.data_);
          }
          onChanged();
        }
        if (other.hasRoldId()) {
          setRoldId(other.getRoldId());
        }
        if (handsBuilder_ == null) {
          if (!other.hands_.isEmpty()) {
            if (hands_.isEmpty()) {
              hands_ = other.hands_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureHandsIsMutable();
              hands_.addAll(other.hands_);
            }
            onChanged();
          }
        } else {
          if (!other.hands_.isEmpty()) {
            if (handsBuilder_.isEmpty()) {
              handsBuilder_.dispose();
              handsBuilder_ = null;
              hands_ = other.hands_;
              bitField0_ = (bitField0_ & ~0x00000010);
              handsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHandsFieldBuilder() : null;
            } else {
              handsBuilder_.addAllMessages(other.hands_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetMjUserResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetMjUserResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .NetKvData scores = 1;
      private java.util.List<NetGame.NetKvData> scores_ =
        java.util.Collections.emptyList();
      private void ensureScoresIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          scores_ = new java.util.ArrayList<NetGame.NetKvData>(scores_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder> scoresBuilder_;

      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public java.util.List<NetGame.NetKvData> getScoresList() {
        if (scoresBuilder_ == null) {
          return java.util.Collections.unmodifiableList(scores_);
        } else {
          return scoresBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public int getScoresCount() {
        if (scoresBuilder_ == null) {
          return scores_.size();
        } else {
          return scoresBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public NetGame.NetKvData getScores(int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);
        } else {
          return scoresBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder setScores(
          int index, NetGame.NetKvData value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.set(index, value);
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder setScores(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.set(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder addScores(NetGame.NetKvData value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder addScores(
          int index, NetGame.NetKvData value) {
        if (scoresBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureScoresIsMutable();
          scores_.add(index, value);
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder addScores(
          NetGame.NetKvData.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder addScores(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.add(index, builderForValue.build());
          onChanged();
        } else {
          scoresBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder addAllScores(
          Iterable<? extends NetGame.NetKvData> values) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          super.addAll(values, scores_);
          onChanged();
        } else {
          scoresBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder clearScores() {
        if (scoresBuilder_ == null) {
          scores_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          scoresBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public Builder removeScores(int index) {
        if (scoresBuilder_ == null) {
          ensureScoresIsMutable();
          scores_.remove(index);
          onChanged();
        } else {
          scoresBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public NetGame.NetKvData.Builder getScoresBuilder(
          int index) {
        return getScoresFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public NetGame.NetKvDataOrBuilder getScoresOrBuilder(
          int index) {
        if (scoresBuilder_ == null) {
          return scores_.get(index);  } else {
          return scoresBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public java.util.List<? extends NetGame.NetKvDataOrBuilder>
           getScoresOrBuilderList() {
        if (scoresBuilder_ != null) {
          return scoresBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(scores_);
        }
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public NetGame.NetKvData.Builder addScoresBuilder() {
        return getScoresFieldBuilder().addBuilder(
            NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public NetGame.NetKvData.Builder addScoresBuilder(
          int index) {
        return getScoresFieldBuilder().addBuilder(
            index, NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData scores = 1;</code>
       */
      public java.util.List<NetGame.NetKvData.Builder>
           getScoresBuilderList() {
        return getScoresFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>
          getScoresFieldBuilder() {
        if (scoresBuilder_ == null) {
          scoresBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>(
                  scores_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          scores_ = null;
        }
        return scoresBuilder_;
      }

      // repeated .NetKvData records = 2;
      private java.util.List<NetGame.NetKvData> records_ =
        java.util.Collections.emptyList();
      private void ensureRecordsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          records_ = new java.util.ArrayList<NetGame.NetKvData>(records_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder> recordsBuilder_;

      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public java.util.List<NetGame.NetKvData> getRecordsList() {
        if (recordsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(records_);
        } else {
          return recordsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public int getRecordsCount() {
        if (recordsBuilder_ == null) {
          return records_.size();
        } else {
          return recordsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public NetGame.NetKvData getRecords(int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);
        } else {
          return recordsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder setRecords(
          int index, NetGame.NetKvData value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.set(index, value);
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder setRecords(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.set(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder addRecords(NetGame.NetKvData value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder addRecords(
          int index, NetGame.NetKvData value) {
        if (recordsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRecordsIsMutable();
          records_.add(index, value);
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder addRecords(
          NetGame.NetKvData.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder addRecords(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.add(index, builderForValue.build());
          onChanged();
        } else {
          recordsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder addAllRecords(
          Iterable<? extends NetGame.NetKvData> values) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          super.addAll(values, records_);
          onChanged();
        } else {
          recordsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder clearRecords() {
        if (recordsBuilder_ == null) {
          records_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          recordsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public Builder removeRecords(int index) {
        if (recordsBuilder_ == null) {
          ensureRecordsIsMutable();
          records_.remove(index);
          onChanged();
        } else {
          recordsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public NetGame.NetKvData.Builder getRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public NetGame.NetKvDataOrBuilder getRecordsOrBuilder(
          int index) {
        if (recordsBuilder_ == null) {
          return records_.get(index);  } else {
          return recordsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public java.util.List<? extends NetGame.NetKvDataOrBuilder>
           getRecordsOrBuilderList() {
        if (recordsBuilder_ != null) {
          return recordsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(records_);
        }
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public NetGame.NetKvData.Builder addRecordsBuilder() {
        return getRecordsFieldBuilder().addBuilder(
            NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public NetGame.NetKvData.Builder addRecordsBuilder(
          int index) {
        return getRecordsFieldBuilder().addBuilder(
            index, NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData records = 2;</code>
       */
      public java.util.List<NetGame.NetKvData.Builder>
           getRecordsBuilderList() {
        return getRecordsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>
          getRecordsFieldBuilder() {
        if (recordsBuilder_ == null) {
          recordsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>(
                  records_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          records_ = null;
        }
        return recordsBuilder_;
      }

      // repeated int32 data = 3;
      private java.util.List<Integer> data_ = java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          data_ = new java.util.ArrayList<Integer>(data_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public java.util.List<Integer>
          getDataList() {
        return java.util.Collections.unmodifiableList(data_);
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public int getDataCount() {
        return data_.size();
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public int getData(int index) {
        return data_.get(index);
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public Builder setData(
          int index, int value) {
        ensureDataIsMutable();
        data_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public Builder addData(int value) {
        ensureDataIsMutable();
        data_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public Builder addAllData(
          Iterable<? extends Integer> values) {
        ensureDataIsMutable();
        super.addAll(values, data_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 data = 3;</code>
       */
      public Builder clearData() {
        data_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional int32 roldId = 4;
      private int roldId_ ;
      /**
       * <code>optional int32 roldId = 4;</code>
       */
      public boolean hasRoldId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 roldId = 4;</code>
       */
      public int getRoldId() {
        return roldId_;
      }
      /**
       * <code>optional int32 roldId = 4;</code>
       */
      public Builder setRoldId(int value) {
        bitField0_ |= 0x00000008;
        roldId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roldId = 4;</code>
       */
      public Builder clearRoldId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        roldId_ = 0;
        onChanged();
        return this;
      }

      // repeated .NetKvData hands = 5;
      private java.util.List<NetGame.NetKvData> hands_ =
        java.util.Collections.emptyList();
      private void ensureHandsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          hands_ = new java.util.ArrayList<NetGame.NetKvData>(hands_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder> handsBuilder_;

      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public java.util.List<NetGame.NetKvData> getHandsList() {
        if (handsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hands_);
        } else {
          return handsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public int getHandsCount() {
        if (handsBuilder_ == null) {
          return hands_.size();
        } else {
          return handsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public NetGame.NetKvData getHands(int index) {
        if (handsBuilder_ == null) {
          return hands_.get(index);
        } else {
          return handsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder setHands(
          int index, NetGame.NetKvData value) {
        if (handsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHandsIsMutable();
          hands_.set(index, value);
          onChanged();
        } else {
          handsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder setHands(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (handsBuilder_ == null) {
          ensureHandsIsMutable();
          hands_.set(index, builderForValue.build());
          onChanged();
        } else {
          handsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder addHands(NetGame.NetKvData value) {
        if (handsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHandsIsMutable();
          hands_.add(value);
          onChanged();
        } else {
          handsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder addHands(
          int index, NetGame.NetKvData value) {
        if (handsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHandsIsMutable();
          hands_.add(index, value);
          onChanged();
        } else {
          handsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder addHands(
          NetGame.NetKvData.Builder builderForValue) {
        if (handsBuilder_ == null) {
          ensureHandsIsMutable();
          hands_.add(builderForValue.build());
          onChanged();
        } else {
          handsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder addHands(
          int index, NetGame.NetKvData.Builder builderForValue) {
        if (handsBuilder_ == null) {
          ensureHandsIsMutable();
          hands_.add(index, builderForValue.build());
          onChanged();
        } else {
          handsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder addAllHands(
          Iterable<? extends NetGame.NetKvData> values) {
        if (handsBuilder_ == null) {
          ensureHandsIsMutable();
          super.addAll(values, hands_);
          onChanged();
        } else {
          handsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder clearHands() {
        if (handsBuilder_ == null) {
          hands_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          handsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public Builder removeHands(int index) {
        if (handsBuilder_ == null) {
          ensureHandsIsMutable();
          hands_.remove(index);
          onChanged();
        } else {
          handsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public NetGame.NetKvData.Builder getHandsBuilder(
          int index) {
        return getHandsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public NetGame.NetKvDataOrBuilder getHandsOrBuilder(
          int index) {
        if (handsBuilder_ == null) {
          return hands_.get(index);  } else {
          return handsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public java.util.List<? extends NetGame.NetKvDataOrBuilder>
           getHandsOrBuilderList() {
        if (handsBuilder_ != null) {
          return handsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hands_);
        }
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public NetGame.NetKvData.Builder addHandsBuilder() {
        return getHandsFieldBuilder().addBuilder(
            NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public NetGame.NetKvData.Builder addHandsBuilder(
          int index) {
        return getHandsFieldBuilder().addBuilder(
            index, NetGame.NetKvData.getDefaultInstance());
      }
      /**
       * <code>repeated .NetKvData hands = 5;</code>
       */
      public java.util.List<NetGame.NetKvData.Builder>
           getHandsBuilderList() {
        return getHandsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>
          getHandsFieldBuilder() {
        if (handsBuilder_ == null) {
          handsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              NetGame.NetKvData, NetGame.NetKvData.Builder, NetGame.NetKvDataOrBuilder>(
                  hands_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          hands_ = null;
        }
        return handsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NetMjUserResult)
    }

    static {
      defaultInstance = new NetMjUserResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetMjUserResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_RQMjREsult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RQMjREsult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetMjUserResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetMjUserResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025proto/NetResult.proto\032\023proto/NetGame.p" +
      "roto\"=\n\nRQMjREsult\022\014\n\004flag\030\001 \001(\005\022!\n\007resu" +
      "lts\030\002 \003(\0132\020.NetMjUserResult\"\203\001\n\017NetMjUse" +
      "rResult\022\032\n\006scores\030\001 \003(\0132\n.NetKvData\022\033\n\007r" +
      "ecords\030\002 \003(\0132\n.NetKvData\022\014\n\004data\030\003 \003(\005\022\016" +
      "\n\006roldId\030\004 \001(\005\022\031\n\005hands\030\005 \003(\0132\n.NetKvDat" +
      "aB\020\n\016com.module.net"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_RQMjREsult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_RQMjREsult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_RQMjREsult_descriptor,
              new String[] { "Flag", "Results", });
          internal_static_NetMjUserResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NetMjUserResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetMjUserResult_descriptor,
              new String[] { "Scores", "Records", "Data", "RoldId", "Hands", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          NetGame.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
