// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/NetParent.proto

package com.net;

public final class NetParent {
  private NetParent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NetCommondOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string sn = 1;
    /**
     * <code>required string sn = 1;</code>
     */
    boolean hasSn();
    /**
     * <code>required string sn = 1;</code>
     */
    String getSn();
    /**
     * <code>required string sn = 1;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();

    // required bytes obj = 2;
    /**
     * <code>required bytes obj = 2;</code>
     */
    boolean hasObj();
    /**
     * <code>required bytes obj = 2;</code>
     */
    com.google.protobuf.ByteString getObj();

    // required int32 seq = 3;
    /**
     * <code>required int32 seq = 3;</code>
     */
    boolean hasSeq();
    /**
     * <code>required int32 seq = 3;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code NetCommond}
   */
  public static final class NetCommond extends
      com.google.protobuf.GeneratedMessage
      implements NetCommondOrBuilder {
    // Use NetCommond.newBuilder() to construct.
    private NetCommond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetCommond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetCommond defaultInstance;
    public static NetCommond getDefaultInstance() {
      return defaultInstance;
    }

    public NetCommond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetCommond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sn_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              obj_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              seq_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetParent.internal_static_NetCommond_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetParent.internal_static_NetCommond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetCommond.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NetCommond> PARSER =
        new com.google.protobuf.AbstractParser<NetCommond>() {
      public NetCommond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetCommond(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NetCommond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string sn = 1;
    public static final int SN_FIELD_NUMBER = 1;
    private Object sn_;
    /**
     * <code>required string sn = 1;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sn = 1;</code>
     */
    public String getSn() {
      Object ref = sn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sn = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      Object ref = sn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes obj = 2;
    public static final int OBJ_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString obj_;
    /**
     * <code>required bytes obj = 2;</code>
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes obj = 2;</code>
     */
    public com.google.protobuf.ByteString getObj() {
      return obj_;
    }

    // required int32 seq = 3;
    public static final int SEQ_FIELD_NUMBER = 3;
    private int seq_;
    /**
     * <code>required int32 seq = 3;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 seq = 3;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private void initFields() {
      sn_ = "";
      obj_ = com.google.protobuf.ByteString.EMPTY;
      seq_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSn()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSeq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, seq_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSnBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, seq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NetCommond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetCommond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetCommond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetCommond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetCommond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetCommond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetCommond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetCommond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetCommond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetCommond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetCommondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetParent.internal_static_NetCommond_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetParent.internal_static_NetCommond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetCommond.class, Builder.class);
      }

      // Construct using com.net.NetParent.NetCommond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        obj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetParent.internal_static_NetCommond_descriptor;
      }

      public NetCommond getDefaultInstanceForType() {
        return NetCommond.getDefaultInstance();
      }

      public NetCommond build() {
        NetCommond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetCommond buildPartial() {
        NetCommond result = new NetCommond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sn_ = sn_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.obj_ = obj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetCommond) {
          return mergeFrom((NetCommond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetCommond other) {
        if (other == NetCommond.getDefaultInstance()) return this;
        if (other.hasSn()) {
          bitField0_ |= 0x00000001;
          sn_ = other.sn_;
          onChanged();
        }
        if (other.hasObj()) {
          setObj(other.getObj());
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSn()) {
          
          return false;
        }
        if (!hasObj()) {
          
          return false;
        }
        if (!hasSeq()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetCommond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetCommond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string sn = 1;
      private Object sn_ = "";
      /**
       * <code>required string sn = 1;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public String getSn() {
        Object ref = sn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder setSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>required string sn = 1;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sn_ = value;
        onChanged();
        return this;
      }

      // required bytes obj = 2;
      private com.google.protobuf.ByteString obj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes obj = 2;</code>
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public com.google.protobuf.ByteString getObj() {
        return obj_;
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public Builder setObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        obj_ = getDefaultInstance().getObj();
        onChanged();
        return this;
      }

      // required int32 seq = 3;
      private int seq_ ;
      /**
       * <code>required int32 seq = 3;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 seq = 3;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>required int32 seq = 3;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000004;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seq = 3;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetCommond)
    }

    static {
      defaultInstance = new NetCommond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetCommond)
  }

  public interface NetErrorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 errorCode = 1;
    /**
     * <code>required int32 errorCode = 1;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>required int32 errorCode = 1;</code>
     */
    int getErrorCode();

    // repeated int32 paramters = 2;
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    java.util.List<Integer> getParamtersList();
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    int getParamtersCount();
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    int getParamters(int index);

    // optional int32 seq = 3;
    /**
     * <code>optional int32 seq = 3;</code>
     */
    boolean hasSeq();
    /**
     * <code>optional int32 seq = 3;</code>
     */
    int getSeq();
  }
  /**
   * Protobuf type {@code NetError}
   */
  public static final class NetError extends
      com.google.protobuf.GeneratedMessage
      implements NetErrorOrBuilder {
    // Use NetError.newBuilder() to construct.
    private NetError(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetError(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetError defaultInstance;
    public static NetError getDefaultInstance() {
      return defaultInstance;
    }

    public NetError getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetError(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errorCode_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paramters_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              paramters_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                paramters_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                paramters_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              seq_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paramters_ = java.util.Collections.unmodifiableList(paramters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetParent.internal_static_NetError_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetParent.internal_static_NetError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetError.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NetError> PARSER =
        new com.google.protobuf.AbstractParser<NetError>() {
      public NetError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetError(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NetError> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 errorCode = 1;
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private int errorCode_;
    /**
     * <code>required int32 errorCode = 1;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 errorCode = 1;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    // repeated int32 paramters = 2;
    public static final int PARAMTERS_FIELD_NUMBER = 2;
    private java.util.List<Integer> paramters_;
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    public java.util.List<Integer>
        getParamtersList() {
      return paramters_;
    }
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    public int getParamtersCount() {
      return paramters_.size();
    }
    /**
     * <code>repeated int32 paramters = 2;</code>
     */
    public int getParamters(int index) {
      return paramters_.get(index);
    }

    // optional int32 seq = 3;
    public static final int SEQ_FIELD_NUMBER = 3;
    private int seq_;
    /**
     * <code>optional int32 seq = 3;</code>
     */
    public boolean hasSeq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 seq = 3;</code>
     */
    public int getSeq() {
      return seq_;
    }

    private void initFields() {
      errorCode_ = 0;
      paramters_ = java.util.Collections.emptyList();
      seq_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrorCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errorCode_);
      }
      for (int i = 0; i < paramters_.size(); i++) {
        output.writeInt32(2, paramters_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, seq_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errorCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < paramters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(paramters_.get(i));
        }
        size += dataSize;
        size += 1 * getParamtersList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, seq_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NetError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetParent.internal_static_NetError_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetParent.internal_static_NetError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetError.class, Builder.class);
      }

      // Construct using com.net.NetParent.NetError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        paramters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        seq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetParent.internal_static_NetError_descriptor;
      }

      public NetError getDefaultInstanceForType() {
        return NetError.getDefaultInstance();
      }

      public NetError build() {
        NetError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetError buildPartial() {
        NetError result = new NetError(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errorCode_ = errorCode_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          paramters_ = java.util.Collections.unmodifiableList(paramters_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.paramters_ = paramters_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.seq_ = seq_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetError) {
          return mergeFrom((NetError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetError other) {
        if (other == NetError.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.paramters_.isEmpty()) {
          if (paramters_.isEmpty()) {
            paramters_ = other.paramters_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureParamtersIsMutable();
            paramters_.addAll(other.paramters_);
          }
          onChanged();
        }
        if (other.hasSeq()) {
          setSeq(other.getSeq());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrorCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetError parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetError) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 errorCode = 1;
      private int errorCode_ ;
      /**
       * <code>required int32 errorCode = 1;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000001;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errorCode = 1;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 paramters = 2;
      private java.util.List<Integer> paramters_ = java.util.Collections.emptyList();
      private void ensureParamtersIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paramters_ = new java.util.ArrayList<Integer>(paramters_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public java.util.List<Integer>
          getParamtersList() {
        return java.util.Collections.unmodifiableList(paramters_);
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public int getParamtersCount() {
        return paramters_.size();
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public int getParamters(int index) {
        return paramters_.get(index);
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public Builder setParamters(
          int index, int value) {
        ensureParamtersIsMutable();
        paramters_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public Builder addParamters(int value) {
        ensureParamtersIsMutable();
        paramters_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public Builder addAllParamters(
          Iterable<? extends Integer> values) {
        ensureParamtersIsMutable();
        super.addAll(values, paramters_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 paramters = 2;</code>
       */
      public Builder clearParamters() {
        paramters_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // optional int32 seq = 3;
      private int seq_ ;
      /**
       * <code>optional int32 seq = 3;</code>
       */
      public boolean hasSeq() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 seq = 3;</code>
       */
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>optional int32 seq = 3;</code>
       */
      public Builder setSeq(int value) {
        bitField0_ |= 0x00000004;
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 seq = 3;</code>
       */
      public Builder clearSeq() {
        bitField0_ = (bitField0_ & ~0x00000004);
        seq_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetError)
    }

    static {
      defaultInstance = new NetError(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetError)
  }

  public interface NetServerCommondOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 uid = 1;
    /**
     * <code>required int32 uid = 1;</code>
     */
    boolean hasUid();
    /**
     * <code>required int32 uid = 1;</code>
     */
    int getUid();

    // required bytes obj = 2;
    /**
     * <code>required bytes obj = 2;</code>
     */
    boolean hasObj();
    /**
     * <code>required bytes obj = 2;</code>
     */
    com.google.protobuf.ByteString getObj();

    // optional string sn = 3;
    /**
     * <code>optional string sn = 3;</code>
     */
    boolean hasSn();
    /**
     * <code>optional string sn = 3;</code>
     */
    String getSn();
    /**
     * <code>optional string sn = 3;</code>
     */
    com.google.protobuf.ByteString
        getSnBytes();
  }
  /**
   * Protobuf type {@code NetServerCommond}
   */
  public static final class NetServerCommond extends
      com.google.protobuf.GeneratedMessage
      implements NetServerCommondOrBuilder {
    // Use NetServerCommond.newBuilder() to construct.
    private NetServerCommond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NetServerCommond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NetServerCommond defaultInstance;
    public static NetServerCommond getDefaultInstance() {
      return defaultInstance;
    }

    public NetServerCommond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NetServerCommond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              obj_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sn_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NetParent.internal_static_NetServerCommond_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NetParent.internal_static_NetServerCommond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NetServerCommond.class, Builder.class);
    }

    public static com.google.protobuf.Parser<NetServerCommond> PARSER =
        new com.google.protobuf.AbstractParser<NetServerCommond>() {
      public NetServerCommond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NetServerCommond(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<NetServerCommond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 uid = 1;
    public static final int UID_FIELD_NUMBER = 1;
    private int uid_;
    /**
     * <code>required int32 uid = 1;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 uid = 1;</code>
     */
    public int getUid() {
      return uid_;
    }

    // required bytes obj = 2;
    public static final int OBJ_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString obj_;
    /**
     * <code>required bytes obj = 2;</code>
     */
    public boolean hasObj() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes obj = 2;</code>
     */
    public com.google.protobuf.ByteString getObj() {
      return obj_;
    }

    // optional string sn = 3;
    public static final int SN_FIELD_NUMBER = 3;
    private Object sn_;
    /**
     * <code>optional string sn = 3;</code>
     */
    public boolean hasSn() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sn = 3;</code>
     */
    public String getSn() {
      Object ref = sn_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sn = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      Object ref = sn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      uid_ = 0;
      obj_ = com.google.protobuf.ByteString.EMPTY;
      sn_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObj()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSnBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, obj_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSnBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static NetServerCommond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetServerCommond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetServerCommond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NetServerCommond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NetServerCommond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetServerCommond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static NetServerCommond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static NetServerCommond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static NetServerCommond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static NetServerCommond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(NetServerCommond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NetServerCommond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements NetServerCommondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NetParent.internal_static_NetServerCommond_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NetParent.internal_static_NetServerCommond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NetServerCommond.class, Builder.class);
      }

      // Construct using com.net.NetParent.NetServerCommond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        obj_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        sn_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NetParent.internal_static_NetServerCommond_descriptor;
      }

      public NetServerCommond getDefaultInstanceForType() {
        return NetServerCommond.getDefaultInstance();
      }

      public NetServerCommond build() {
        NetServerCommond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public NetServerCommond buildPartial() {
        NetServerCommond result = new NetServerCommond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.obj_ = obj_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sn_ = sn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NetServerCommond) {
          return mergeFrom((NetServerCommond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NetServerCommond other) {
        if (other == NetServerCommond.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasObj()) {
          setObj(other.getObj());
        }
        if (other.hasSn()) {
          bitField0_ |= 0x00000004;
          sn_ = other.sn_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasObj()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NetServerCommond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NetServerCommond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 uid = 1;
      private int uid_ ;
      /**
       * <code>required int32 uid = 1;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder setUid(int value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 uid = 1;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0;
        onChanged();
        return this;
      }

      // required bytes obj = 2;
      private com.google.protobuf.ByteString obj_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes obj = 2;</code>
       */
      public boolean hasObj() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public com.google.protobuf.ByteString getObj() {
        return obj_;
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public Builder setObj(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        obj_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes obj = 2;</code>
       */
      public Builder clearObj() {
        bitField0_ = (bitField0_ & ~0x00000002);
        obj_ = getDefaultInstance().getObj();
        onChanged();
        return this;
      }

      // optional string sn = 3;
      private Object sn_ = "";
      /**
       * <code>optional string sn = 3;</code>
       */
      public boolean hasSn() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sn = 3;</code>
       */
      public String getSn() {
        Object ref = sn_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sn_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string sn = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSnBytes() {
        Object ref = sn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sn = 3;</code>
       */
      public Builder setSn(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 3;</code>
       */
      public Builder clearSn() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sn_ = getDefaultInstance().getSn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sn = 3;</code>
       */
      public Builder setSnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sn_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NetServerCommond)
    }

    static {
      defaultInstance = new NetServerCommond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NetServerCommond)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetCommond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetCommond_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetError_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetError_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NetServerCommond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NetServerCommond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025proto/NetParent.proto\"2\n\nNetCommond\022\n\n" +
      "\002sn\030\001 \002(\t\022\013\n\003obj\030\002 \002(\014\022\013\n\003seq\030\003 \002(\005\"=\n\010N" +
      "etError\022\021\n\terrorCode\030\001 \002(\005\022\021\n\tparamters\030" +
      "\002 \003(\005\022\013\n\003seq\030\003 \001(\005\"8\n\020NetServerCommond\022\013" +
      "\n\003uid\030\001 \002(\005\022\013\n\003obj\030\002 \002(\014\022\n\n\002sn\030\003 \001(\tB\024\n\007" +
      "com.netB\tNetParent"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NetCommond_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NetCommond_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetCommond_descriptor,
              new String[] { "Sn", "Obj", "Seq", });
          internal_static_NetError_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_NetError_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetError_descriptor,
              new String[] { "ErrorCode", "Paramters", "Seq", });
          internal_static_NetServerCommond_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_NetServerCommond_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NetServerCommond_descriptor,
              new String[] { "Uid", "Obj", "Sn", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
